package com.test.app.model;

import java.util.Date;

public class ProgramExt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.id
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.code
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.name
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.ipd_name
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String ipdName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.type
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.status
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.episode_number
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private Integer episodeNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.actor
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String actor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.director
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String director;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.region
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.language
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.genre
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String genre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.keywords
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String keywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.rating
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String rating;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.small_image1
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String smallImage1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.small_image2
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String smallImage2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.big_image1
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String bigImage1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.big_image2
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String bigImage2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.reserve1
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String reserve1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.reserve2
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String reserve2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.reserve3
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String reserve3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.reserve4
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String reserve4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.reserve5
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String reserve5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.SEARCH_NAME
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String searchName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.year
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.content_type
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String contentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.tags
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String tags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.length
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private Long length;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.subtitleType
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private Integer subtitletype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.subtitleURL
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String subtitleurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.onlined_protocol
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private Long onlinedProtocol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.update_time
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.onlined_bitrate
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String onlinedBitrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.price
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.p_code
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String pCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.small_image3
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String smallImage3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.big_image3
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String bigImage3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.onlined_protocol_audio
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String onlinedProtocolAudio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.old_id
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String oldId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.r_media_code
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String rMediaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.mi_small_image
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String miSmallImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.mi_big_image
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String miBigImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.update_episode_number
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private Integer updateEpisodeNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.xbox_image1
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String xboxImage1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.xbox_image2
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String xboxImage2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.xbox_image3
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String xboxImage3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.xbox_image4
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String xboxImage4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.xbox_image5
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String xboxImage5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.xbox_image6
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String xboxImage6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.xbox_image7
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String xboxImage7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.xbox_image_1138_640
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String xboxImage1138640;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.xbox_image_424_640
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String xboxImage424640;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.xbox_image_640_640
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String xboxImage640640;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.xbox_image_424_100
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String xboxImage424100;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.category
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tv_program_ext.copyright_type
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    private Integer copyrightType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.id
     *
     * @return the value of tv_program_ext.id
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.id
     *
     * @param id the value for tv_program_ext.id
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.code
     *
     * @return the value of tv_program_ext.code
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.code
     *
     * @param code the value for tv_program_ext.code
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.name
     *
     * @return the value of tv_program_ext.name
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.name
     *
     * @param name the value for tv_program_ext.name
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.ipd_name
     *
     * @return the value of tv_program_ext.ipd_name
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getIpdName() {
        return ipdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.ipd_name
     *
     * @param ipdName the value for tv_program_ext.ipd_name
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setIpdName(String ipdName) {
        this.ipdName = ipdName == null ? null : ipdName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.type
     *
     * @return the value of tv_program_ext.type
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.type
     *
     * @param type the value for tv_program_ext.type
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.status
     *
     * @return the value of tv_program_ext.status
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.status
     *
     * @param status the value for tv_program_ext.status
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.episode_number
     *
     * @return the value of tv_program_ext.episode_number
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public Integer getEpisodeNumber() {
        return episodeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.episode_number
     *
     * @param episodeNumber the value for tv_program_ext.episode_number
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setEpisodeNumber(Integer episodeNumber) {
        this.episodeNumber = episodeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.actor
     *
     * @return the value of tv_program_ext.actor
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getActor() {
        return actor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.actor
     *
     * @param actor the value for tv_program_ext.actor
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setActor(String actor) {
        this.actor = actor == null ? null : actor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.director
     *
     * @return the value of tv_program_ext.director
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getDirector() {
        return director;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.director
     *
     * @param director the value for tv_program_ext.director
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setDirector(String director) {
        this.director = director == null ? null : director.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.region
     *
     * @return the value of tv_program_ext.region
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.region
     *
     * @param region the value for tv_program_ext.region
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.language
     *
     * @return the value of tv_program_ext.language
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.language
     *
     * @param language the value for tv_program_ext.language
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.genre
     *
     * @return the value of tv_program_ext.genre
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getGenre() {
        return genre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.genre
     *
     * @param genre the value for tv_program_ext.genre
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setGenre(String genre) {
        this.genre = genre == null ? null : genre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.keywords
     *
     * @return the value of tv_program_ext.keywords
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.keywords
     *
     * @param keywords the value for tv_program_ext.keywords
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.rating
     *
     * @return the value of tv_program_ext.rating
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.rating
     *
     * @param rating the value for tv_program_ext.rating
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setRating(String rating) {
        this.rating = rating == null ? null : rating.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.small_image1
     *
     * @return the value of tv_program_ext.small_image1
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getSmallImage1() {
        return smallImage1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.small_image1
     *
     * @param smallImage1 the value for tv_program_ext.small_image1
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setSmallImage1(String smallImage1) {
        this.smallImage1 = smallImage1 == null ? null : smallImage1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.small_image2
     *
     * @return the value of tv_program_ext.small_image2
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getSmallImage2() {
        return smallImage2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.small_image2
     *
     * @param smallImage2 the value for tv_program_ext.small_image2
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setSmallImage2(String smallImage2) {
        this.smallImage2 = smallImage2 == null ? null : smallImage2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.big_image1
     *
     * @return the value of tv_program_ext.big_image1
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getBigImage1() {
        return bigImage1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.big_image1
     *
     * @param bigImage1 the value for tv_program_ext.big_image1
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setBigImage1(String bigImage1) {
        this.bigImage1 = bigImage1 == null ? null : bigImage1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.big_image2
     *
     * @return the value of tv_program_ext.big_image2
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getBigImage2() {
        return bigImage2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.big_image2
     *
     * @param bigImage2 the value for tv_program_ext.big_image2
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setBigImage2(String bigImage2) {
        this.bigImage2 = bigImage2 == null ? null : bigImage2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.reserve1
     *
     * @return the value of tv_program_ext.reserve1
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getReserve1() {
        return reserve1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.reserve1
     *
     * @param reserve1 the value for tv_program_ext.reserve1
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setReserve1(String reserve1) {
        this.reserve1 = reserve1 == null ? null : reserve1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.reserve2
     *
     * @return the value of tv_program_ext.reserve2
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getReserve2() {
        return reserve2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.reserve2
     *
     * @param reserve2 the value for tv_program_ext.reserve2
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setReserve2(String reserve2) {
        this.reserve2 = reserve2 == null ? null : reserve2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.reserve3
     *
     * @return the value of tv_program_ext.reserve3
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getReserve3() {
        return reserve3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.reserve3
     *
     * @param reserve3 the value for tv_program_ext.reserve3
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setReserve3(String reserve3) {
        this.reserve3 = reserve3 == null ? null : reserve3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.reserve4
     *
     * @return the value of tv_program_ext.reserve4
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getReserve4() {
        return reserve4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.reserve4
     *
     * @param reserve4 the value for tv_program_ext.reserve4
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setReserve4(String reserve4) {
        this.reserve4 = reserve4 == null ? null : reserve4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.reserve5
     *
     * @return the value of tv_program_ext.reserve5
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getReserve5() {
        return reserve5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.reserve5
     *
     * @param reserve5 the value for tv_program_ext.reserve5
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setReserve5(String reserve5) {
        this.reserve5 = reserve5 == null ? null : reserve5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.SEARCH_NAME
     *
     * @return the value of tv_program_ext.SEARCH_NAME
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getSearchName() {
        return searchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.SEARCH_NAME
     *
     * @param searchName the value for tv_program_ext.SEARCH_NAME
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setSearchName(String searchName) {
        this.searchName = searchName == null ? null : searchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.year
     *
     * @return the value of tv_program_ext.year
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.year
     *
     * @param year the value for tv_program_ext.year
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.content_type
     *
     * @return the value of tv_program_ext.content_type
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.content_type
     *
     * @param contentType the value for tv_program_ext.content_type
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setContentType(String contentType) {
        this.contentType = contentType == null ? null : contentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.tags
     *
     * @return the value of tv_program_ext.tags
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.tags
     *
     * @param tags the value for tv_program_ext.tags
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.length
     *
     * @return the value of tv_program_ext.length
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public Long getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.length
     *
     * @param length the value for tv_program_ext.length
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setLength(Long length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.subtitleType
     *
     * @return the value of tv_program_ext.subtitleType
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public Integer getSubtitletype() {
        return subtitletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.subtitleType
     *
     * @param subtitletype the value for tv_program_ext.subtitleType
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setSubtitletype(Integer subtitletype) {
        this.subtitletype = subtitletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.subtitleURL
     *
     * @return the value of tv_program_ext.subtitleURL
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getSubtitleurl() {
        return subtitleurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.subtitleURL
     *
     * @param subtitleurl the value for tv_program_ext.subtitleURL
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setSubtitleurl(String subtitleurl) {
        this.subtitleurl = subtitleurl == null ? null : subtitleurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.onlined_protocol
     *
     * @return the value of tv_program_ext.onlined_protocol
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public Long getOnlinedProtocol() {
        return onlinedProtocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.onlined_protocol
     *
     * @param onlinedProtocol the value for tv_program_ext.onlined_protocol
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setOnlinedProtocol(Long onlinedProtocol) {
        this.onlinedProtocol = onlinedProtocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.update_time
     *
     * @return the value of tv_program_ext.update_time
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.update_time
     *
     * @param updateTime the value for tv_program_ext.update_time
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.onlined_bitrate
     *
     * @return the value of tv_program_ext.onlined_bitrate
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getOnlinedBitrate() {
        return onlinedBitrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.onlined_bitrate
     *
     * @param onlinedBitrate the value for tv_program_ext.onlined_bitrate
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setOnlinedBitrate(String onlinedBitrate) {
        this.onlinedBitrate = onlinedBitrate == null ? null : onlinedBitrate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.price
     *
     * @return the value of tv_program_ext.price
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.price
     *
     * @param price the value for tv_program_ext.price
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.p_code
     *
     * @return the value of tv_program_ext.p_code
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getpCode() {
        return pCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.p_code
     *
     * @param pCode the value for tv_program_ext.p_code
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setpCode(String pCode) {
        this.pCode = pCode == null ? null : pCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.small_image3
     *
     * @return the value of tv_program_ext.small_image3
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getSmallImage3() {
        return smallImage3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.small_image3
     *
     * @param smallImage3 the value for tv_program_ext.small_image3
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setSmallImage3(String smallImage3) {
        this.smallImage3 = smallImage3 == null ? null : smallImage3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.big_image3
     *
     * @return the value of tv_program_ext.big_image3
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getBigImage3() {
        return bigImage3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.big_image3
     *
     * @param bigImage3 the value for tv_program_ext.big_image3
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setBigImage3(String bigImage3) {
        this.bigImage3 = bigImage3 == null ? null : bigImage3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.onlined_protocol_audio
     *
     * @return the value of tv_program_ext.onlined_protocol_audio
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getOnlinedProtocolAudio() {
        return onlinedProtocolAudio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.onlined_protocol_audio
     *
     * @param onlinedProtocolAudio the value for tv_program_ext.onlined_protocol_audio
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setOnlinedProtocolAudio(String onlinedProtocolAudio) {
        this.onlinedProtocolAudio = onlinedProtocolAudio == null ? null : onlinedProtocolAudio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.old_id
     *
     * @return the value of tv_program_ext.old_id
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getOldId() {
        return oldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.old_id
     *
     * @param oldId the value for tv_program_ext.old_id
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setOldId(String oldId) {
        this.oldId = oldId == null ? null : oldId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.r_media_code
     *
     * @return the value of tv_program_ext.r_media_code
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getrMediaCode() {
        return rMediaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.r_media_code
     *
     * @param rMediaCode the value for tv_program_ext.r_media_code
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setrMediaCode(String rMediaCode) {
        this.rMediaCode = rMediaCode == null ? null : rMediaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.mi_small_image
     *
     * @return the value of tv_program_ext.mi_small_image
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getMiSmallImage() {
        return miSmallImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.mi_small_image
     *
     * @param miSmallImage the value for tv_program_ext.mi_small_image
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setMiSmallImage(String miSmallImage) {
        this.miSmallImage = miSmallImage == null ? null : miSmallImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.mi_big_image
     *
     * @return the value of tv_program_ext.mi_big_image
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getMiBigImage() {
        return miBigImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.mi_big_image
     *
     * @param miBigImage the value for tv_program_ext.mi_big_image
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setMiBigImage(String miBigImage) {
        this.miBigImage = miBigImage == null ? null : miBigImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.update_episode_number
     *
     * @return the value of tv_program_ext.update_episode_number
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public Integer getUpdateEpisodeNumber() {
        return updateEpisodeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.update_episode_number
     *
     * @param updateEpisodeNumber the value for tv_program_ext.update_episode_number
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setUpdateEpisodeNumber(Integer updateEpisodeNumber) {
        this.updateEpisodeNumber = updateEpisodeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.xbox_image1
     *
     * @return the value of tv_program_ext.xbox_image1
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getXboxImage1() {
        return xboxImage1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.xbox_image1
     *
     * @param xboxImage1 the value for tv_program_ext.xbox_image1
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setXboxImage1(String xboxImage1) {
        this.xboxImage1 = xboxImage1 == null ? null : xboxImage1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.xbox_image2
     *
     * @return the value of tv_program_ext.xbox_image2
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getXboxImage2() {
        return xboxImage2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.xbox_image2
     *
     * @param xboxImage2 the value for tv_program_ext.xbox_image2
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setXboxImage2(String xboxImage2) {
        this.xboxImage2 = xboxImage2 == null ? null : xboxImage2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.xbox_image3
     *
     * @return the value of tv_program_ext.xbox_image3
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getXboxImage3() {
        return xboxImage3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.xbox_image3
     *
     * @param xboxImage3 the value for tv_program_ext.xbox_image3
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setXboxImage3(String xboxImage3) {
        this.xboxImage3 = xboxImage3 == null ? null : xboxImage3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.xbox_image4
     *
     * @return the value of tv_program_ext.xbox_image4
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getXboxImage4() {
        return xboxImage4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.xbox_image4
     *
     * @param xboxImage4 the value for tv_program_ext.xbox_image4
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setXboxImage4(String xboxImage4) {
        this.xboxImage4 = xboxImage4 == null ? null : xboxImage4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.xbox_image5
     *
     * @return the value of tv_program_ext.xbox_image5
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getXboxImage5() {
        return xboxImage5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.xbox_image5
     *
     * @param xboxImage5 the value for tv_program_ext.xbox_image5
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setXboxImage5(String xboxImage5) {
        this.xboxImage5 = xboxImage5 == null ? null : xboxImage5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.xbox_image6
     *
     * @return the value of tv_program_ext.xbox_image6
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getXboxImage6() {
        return xboxImage6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.xbox_image6
     *
     * @param xboxImage6 the value for tv_program_ext.xbox_image6
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setXboxImage6(String xboxImage6) {
        this.xboxImage6 = xboxImage6 == null ? null : xboxImage6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.xbox_image7
     *
     * @return the value of tv_program_ext.xbox_image7
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getXboxImage7() {
        return xboxImage7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.xbox_image7
     *
     * @param xboxImage7 the value for tv_program_ext.xbox_image7
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setXboxImage7(String xboxImage7) {
        this.xboxImage7 = xboxImage7 == null ? null : xboxImage7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.xbox_image_1138_640
     *
     * @return the value of tv_program_ext.xbox_image_1138_640
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getXboxImage1138640() {
        return xboxImage1138640;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.xbox_image_1138_640
     *
     * @param xboxImage1138640 the value for tv_program_ext.xbox_image_1138_640
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setXboxImage1138640(String xboxImage1138640) {
        this.xboxImage1138640 = xboxImage1138640 == null ? null : xboxImage1138640.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.xbox_image_424_640
     *
     * @return the value of tv_program_ext.xbox_image_424_640
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getXboxImage424640() {
        return xboxImage424640;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.xbox_image_424_640
     *
     * @param xboxImage424640 the value for tv_program_ext.xbox_image_424_640
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setXboxImage424640(String xboxImage424640) {
        this.xboxImage424640 = xboxImage424640 == null ? null : xboxImage424640.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.xbox_image_640_640
     *
     * @return the value of tv_program_ext.xbox_image_640_640
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getXboxImage640640() {
        return xboxImage640640;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.xbox_image_640_640
     *
     * @param xboxImage640640 the value for tv_program_ext.xbox_image_640_640
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setXboxImage640640(String xboxImage640640) {
        this.xboxImage640640 = xboxImage640640 == null ? null : xboxImage640640.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.xbox_image_424_100
     *
     * @return the value of tv_program_ext.xbox_image_424_100
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getXboxImage424100() {
        return xboxImage424100;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.xbox_image_424_100
     *
     * @param xboxImage424100 the value for tv_program_ext.xbox_image_424_100
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setXboxImage424100(String xboxImage424100) {
        this.xboxImage424100 = xboxImage424100 == null ? null : xboxImage424100.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.category
     *
     * @return the value of tv_program_ext.category
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.category
     *
     * @param category the value for tv_program_ext.category
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tv_program_ext.copyright_type
     *
     * @return the value of tv_program_ext.copyright_type
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public Integer getCopyrightType() {
        return copyrightType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tv_program_ext.copyright_type
     *
     * @param copyrightType the value for tv_program_ext.copyright_type
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    public void setCopyrightType(Integer copyrightType) {
        this.copyrightType = copyrightType;
    }
}