package com.test.app.model;

import java.util.Date;

public class Video {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.id
     *
     * @mbggenerated Wed Jul 27 17:43:47 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.name
     *
     * @mbggenerated Wed Jul 27 17:43:47 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.play_url
     *
     * @mbggenerated Wed Jul 27 17:43:47 CST 2016
     */
    private String playUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.create_time
     *
     * @mbggenerated Wed Jul 27 17:43:47 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.id
     *
     * @return the value of video.id
     *
     * @mbggenerated Wed Jul 27 17:43:47 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.id
     *
     * @param id the value for video.id
     *
     * @mbggenerated Wed Jul 27 17:43:47 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.name
     *
     * @return the value of video.name
     *
     * @mbggenerated Wed Jul 27 17:43:47 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.name
     *
     * @param name the value for video.name
     *
     * @mbggenerated Wed Jul 27 17:43:47 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.play_url
     *
     * @return the value of video.play_url
     *
     * @mbggenerated Wed Jul 27 17:43:47 CST 2016
     */
    public String getPlayUrl() {
        return playUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.play_url
     *
     * @param playUrl the value for video.play_url
     *
     * @mbggenerated Wed Jul 27 17:43:47 CST 2016
     */
    public void setPlayUrl(String playUrl) {
        this.playUrl = playUrl == null ? null : playUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.create_time
     *
     * @return the value of video.create_time
     *
     * @mbggenerated Wed Jul 27 17:43:47 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.create_time
     *
     * @param createTime the value for video.create_time
     *
     * @mbggenerated Wed Jul 27 17:43:47 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}