package com.test.app.dao;

import com.test.app.model.ProgramExt;
import com.test.app.model.ProgramExtExample;
import com.test.app.model.ProgramExtWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProgramExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tv_program_ext
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    int countByExample(ProgramExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tv_program_ext
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    int deleteByExample(ProgramExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tv_program_ext
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tv_program_ext
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    int insert(ProgramExtWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tv_program_ext
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    int insertSelective(ProgramExtWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tv_program_ext
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    List<ProgramExtWithBLOBs> selectByExampleWithBLOBs(ProgramExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tv_program_ext
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    List<ProgramExt> selectByExample(ProgramExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tv_program_ext
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    ProgramExtWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tv_program_ext
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    int updateByExampleSelective(@Param("record") ProgramExtWithBLOBs record, @Param("example") ProgramExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tv_program_ext
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") ProgramExtWithBLOBs record, @Param("example") ProgramExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tv_program_ext
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    int updateByExample(@Param("record") ProgramExt record, @Param("example") ProgramExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tv_program_ext
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    int updateByPrimaryKeySelective(ProgramExtWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tv_program_ext
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(ProgramExtWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tv_program_ext
     *
     * @mbggenerated Tue Jul 12 14:04:26 CST 2016
     */
    int updateByPrimaryKey(ProgramExt record);
}